//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoueurFootDATA
{
    using System;
    
    public partial class GetClub_Result2
    {
        public int Id { get; set; }
        public string NomEquipe { get; set; }
        public string SurNom { get; set; }
        public string Abreviation { get; set; }
        public System.DateTime DateFondation { get; set; }
        public string PDG { get; set; }
        public string Entraineur { get; set; }
        public string NomStade { get; set; }
        public int NombreCoupeNation { get; set; }
        public int NombreCoupeContinental { get; set; }
        public int FkPays { get; set; }
        public string NomPays { get; set; }
        public int FkContinent { get; set; }
        public string NomContinent { get; set; }
    }
}
