//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoueurFootDATA
{
    using System;
    
    public partial class GetPlayer_Result1
    {
        public int Id { get; set; }
        public string NomJoueur { get; set; }
        public string PrenomJoueur { get; set; }
        public System.DateTime DateNaissance { get; set; }
        public System.DateTime DateDebutContrat { get; set; }
        public System.DateTime DateFinContrat { get; set; }
        public int SalaireHebdomadaire { get; set; }
        public string NomEquipe { get; set; }
        public string PositionNom { get; set; }
        public string NomPays { get; set; }
        public string NomContinent { get; set; }
        public string NomAgent { get; set; }
        public string PrenomAgent { get; set; }
    }
}
